services:
  neo4j:
    image: neo4j:5.15-community
    container_name: odoo-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/odoo_password_2024
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  neo4j_data:
